name: GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # запускается каждый день
  push:
    branches:
      - main  # или другая твоя основная ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate contribution snake
      uses: platane/snk@v1.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        output: ./github-contribution-grid-snake.svg

    - name: Commit and push if changed
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add github-contribution-grid-snake.svg
        git commit -m "Update contribution snake" || echo "No changes to commit"
        git push
